//! What gets written down, and what does not.

use serde::{Deserialize, Serialize};

use crate::types::message::{Message, ToolCall};

/// Position in the journal. Monotonic, assigned on append.
///
/// Not a timestamp: two entries can share a millisecond, and ordering is the
/// property everything else depends on.
#[derive(
    Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize, Default,
)]
pub struct EntryId(pub u64);

impl std::fmt::Display for EntryId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "#{}", self.0)
    }
}

/// Why the agent was woken.
///
/// Open-ended on purpose: a heartbeat, a person, a finished tool, a file
/// changing, a peer. The agent does not need to know how it was reached, only
/// that it was — which is what keeps this from turning into an event framework.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum WakeReason {
    /// The periodic timer, with nothing else to report.
    Heartbeat,
    /// A person said something.
    User,
    /// Something outside gen2 asked for attention. The string is the caller's
    /// to define; gen2 only carries it.
    External(String),
}

/// Where an input came from.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum InputSource {
    /// Typed by a person.
    User,
    /// Generated by the agent itself on waking — a self-prompt.
    ///
    /// Recorded so a replay can tell "it decided to do this" from "it was
    /// asked to do this", which are very different things when reading back
    /// why an autonomous process did something.
    SelfPrompt,
    /// Delivered by something else.
    External(String),
}

/// One durable fact.
///
/// Deliberately narrower than the runtime's event stream. Streaming deltas,
/// per-token progress and generation start/stop are real events but they are
/// not *facts about the conversation* — writing them here would freeze
/// today's streaming internals into a format that has to be read back in a
/// year. What is written down is what would be needed to reconstruct the
/// agent, and nothing else.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind", rename_all = "snake_case")]
#[non_exhaustive]
pub enum JournalEntry {
    /// Something arrived for the agent to act on.
    Input {
        source: InputSource,
        content: Message,
    },
    /// The model spoke.
    Assistant { message: Message },
    /// The model asked for a tool.
    ToolCall {
        /// The model's own id for this call. What ties a result back to it.
        id: String,
        tool: String,
        args: serde_json::Value,
    },
    /// A tool answered.
    ToolResult {
        /// The `ToolCall::id` this answers.
        id: String,
        tool: String,
        /// What the model is shown.
        ///
        /// Stored as the rendered text rather than as a `ToolOutput`, so the
        /// durable format does not inherit that type's shape. A journal read
        /// back in a year should not need this crate's current internals to
        /// make sense of it.
        output: String,
        /// Whether the tool succeeded. A failure the model can act on is still
        /// a result, and the distinction matters when reading back what
        /// happened.
        ok: bool,
    },
    /// The agent recorded something for its future self.
    ScratchSet { key: String, value: String },
    /// ...or took it back.
    ScratchDelete { key: String },
    /// The agent was woken.
    Wake { reason: WakeReason },
}

impl JournalEntry {
    /// The call id this entry belongs to, if any.
    ///
    /// The pairing key. [`super::Turn`] uses it to keep a call and its result
    /// together, which is the invariant the whole module exists to hold.
    pub fn call_id(&self) -> Option<&str> {
        match self {
            Self::ToolCall { id, .. } | Self::ToolResult { id, .. } => Some(id),
            _ => None,
        }
    }

    /// Whether this entry contributes to what the model is shown.
    ///
    /// `Wake` and the scratch mutations are bookkeeping: they say why the
    /// agent acted and what it remembered, but replaying ten thousand
    /// heartbeats at a model is how a transcript turns to noise. They stay in
    /// the journal and out of the context — which is the point of the journal
    /// being a different thing from the transcript.
    pub fn is_conversational(&self) -> bool {
        matches!(
            self,
            Self::Input { .. }
                | Self::Assistant { .. }
                | Self::ToolCall { .. }
                | Self::ToolResult { .. }
        )
    }
}

/// A journal entry with its position and time.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Record {
    pub id: EntryId,
    /// Unix seconds. For humans reading back, not for ordering — see
    /// [`EntryId`].
    pub at: i64,
    /// Nested rather than `#[serde(flatten)]`: a `ToolCall` carries its own
    /// `id` — the model's call id — and flattening put two different `id`
    /// fields in one object. Serialising succeeded and reading back failed
    /// with "duplicate field", so the durable format was write-only for
    /// exactly the entries the pairing invariant depends on.
    pub entry: JournalEntry,
}

impl Record {
    /// The messages this record contributes to a transcript, in order.
    ///
    /// Empty for anything non-conversational.
    pub(crate) fn to_messages(&self) -> Vec<Message> {
        match &self.entry {
            JournalEntry::Input { content, .. } => vec![content.clone()],
            JournalEntry::Assistant { message } => vec![message.clone()],
            JournalEntry::ToolCall { id, tool, args } => {
                vec![Message::assistant_tool_calls(vec![ToolCall {
                    id: id.clone(),
                    r#type: "function".into(),
                    function: crate::types::message::FunctionDefinition {
                        description: None,
                        name: tool.clone(),
                        arguments: args.clone(),
                    },
                }])]
            }
            JournalEntry::ToolResult { id, output, .. } => {
                vec![Message::tool_result_for(id.clone(), output.clone())]
            }
            _ => Vec::new(),
        }
    }
}
