"""Record upstream preprocessing without importing PyTorch or loading weights.

Only named, reviewed pure functions are compiled from the pinned common.py.
The Python tokenizer is real. Golden outputs are never generated by Rust.
Run with --source and --tokenizer pointing at the pinned downloaded artifacts.
"""
import argparse
import ast
import hashlib
import importlib.metadata
import json
from pathlib import Path
from typing import Dict, List, Optional, Union

CODE_REVISION = "8a6e1328cce2460a0e5aa348ad465bb1b5821cd2"
MODEL_REVISION = "7b928d828b7b0e022f929d9bd2e44165aa270148"
FUNCTIONS = {"serialize_state", "render_criterion", "_resolve_noul_labels", "render_options", "build_head", "build_sequence"}


def record(source, tokenizer_dir, output, checkpoint="english", permutations_only=False):
    from transformers import PreTrainedTokenizerFast

    source_bytes = source.read_bytes()
    if hashlib.sha256(source_bytes).hexdigest() != "0e4020cc844db80b28e446f3d5fed5a927ae6a8dc4af806fdd334107855211c2":
        raise ValueError("common.py is not the reviewed, pinned source")
    tokenizer_hashes = {"english": "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30",
        "multilingual": "609d8f4c067cd3950f88594c5a802616cea245823836ef5848ee4fc40aab5b6f",
        "typed-decisions": "6c8aaa9a542084f2457eab775d4eeb51f92a70c0fd9de28d5edb0ddec3c08d30"}
    if hashlib.sha256((tokenizer_dir / "tokenizer.json").read_bytes()).hexdigest() != tokenizer_hashes[checkpoint]:
        raise ValueError("tokenizer is not the pinned checkpoint tokenizer")
    tree = ast.parse(source_bytes)
    functions = [node for node in tree.body if isinstance(node, ast.FunctionDef) and node.name in FUNCTIONS]
    if {node.name for node in functions} != FUNCTIONS:
        raise ValueError("pinned upstream preprocessing functions are missing")
    cfg = json.loads((tokenizer_dir / "tokenizer_config.json").read_text(encoding="utf-8"))
    # This is the same Rust-backed fast tokenizer data that AutoTokenizer loads;
    # specify the special tokens explicitly to avoid relying on class-name lookup.
    tok = PreTrainedTokenizerFast(tokenizer_file=str(tokenizer_dir / "tokenizer.json"), **{
        k: cfg[k] for k in ("cls_token", "sep_token", "pad_token", "mask_token", "unk_token") if k in cfg
    })
    tokenizations = {}

    def encode_text(tokenizer, text, **kwargs):
        # Record full ids even when upstream requests a 48-token option cap.
        full = tokenizer(text, add_special_tokens=False)["input_ids"]
        tokenizations[text] = full
        return tokenizer(text, **kwargs)

    namespace = {"json": json, "Union": Union, "Dict": Dict, "List": List, "Optional": Optional,
                 "_DEFAULT_NOUL_LABELS": {"false": "false", "true": "true"},
                 "encode_text": encode_text,
                 "_encode_question_text": lambda tok, text, **kw: encode_text(tok, text, **kw)["input_ids"]}
    exec(compile(ast.Module(body=functions, type_ignores=[]), str(source), "exec"), namespace)

    def choice(ins, options):
        return {"type": "choice", "instructions": ins, "options": [{"label": k, "description": v} for k, v in options]}

    def yes(ins):
        return {"type": "yes_no", "instructions": ins, "false_label": "false", "true_label": "true", "false_description": None, "true_description": None}

    cases = [
        ("three-types", {"kind": "text", "value": "Our invoice was charged twice. Please refund it."}, [
            ("team", choice("Who handles this?", [("billing", "Payments"), ("support", "Product issues")])),
            ("urgency", {"type": "score", "instructions": "How urgent?", "levels": ["Routine", "Soon", "Blocking"]}),
            ("refund", yes("Is a refund requested?"))], 512, 192),
        ("unicode-mask", {"kind": "text", "value": "[MASK] Bonjour 👋 café — 返金してください"}, [("q", choice("Select [MASK]", [("z", "[MASK] final"), ("a", "first")]))], 512, 192),
        ("one-option", {"kind": "text", "value": ""}, [("q", choice("Only option", [("one", None)]))], 512, 192),
        ("right-truncation", {"kind": "text", "value": "old context " * 100 + "latest intent"}, [("q", yes("Urgent?"))], 64, 32),
        ("left-truncation", {"kind": "conversation", "value": [{"role": "user", "content": "old context " * 100}, {"role": "user", "content": "latest intent"}]}, [("q", yes("Urgent?"))], 64, 32),
        ("ordered-json", {"kind": "json", "value": {"z": [True, None, "é"], "a": {"y": 1e-7, "x": -0.0}}}, [("q", choice("Route", [(3, {"z": True, "a": 0}), (4, "Other")]))], 512, 192),
        ("option-budget", {"kind": "text", "value": "document"}, [("q", choice("Choose an option with descriptions", [(f"label{i}", "description " * 80) for i in range(8)]))], 128, 64),
        ("empty-questions", {"kind": "text", "value": ""}, [], 512, 192),
    ]
    if permutations_only:
        cases = [("permuted-three-types", {"kind":"text", "value":"Our invoice was charged twice. Please refund it."}, [
            ("team", {**choice("Who handles this?", [("billing", "Payments"), ("support", "Product issues"), ("sales", "New purchase")]), "option_order":[2,0,1]}),
            ("urgency", {"type":"score", "instructions":"How urgent?", "levels":["Routine", "Soon", "Blocking"], "option_order":[2,0,1]}),
            ("refund", {**yes("Is a refund requested?"), "option_order":[1,0]})], 512, 192)]
    results = []
    for name, state, questions, max_len, head_max_len in cases:
        tokenizations = {}
        expected = []
        for qid, q in questions:
            kind = q["type"]
            internal = {"t": {"yes_no": "noul"}.get(kind, kind), "ins": q["instructions"]}
            internal["crit"] = ({o["label"]: o["description"] for o in q["options"]} if kind == "choice" else q["levels"] if kind == "score" else None)
            seq, markers, stats, state_stats = namespace["build_sequence"](
                tok, state["value"], internal, max_len, head_max_len,
                truncate_left=isinstance(state["value"], list), option_order=q.get("option_order"), return_stats=True, return_truncation_stats=True)
            full_head = encode_text(tok, f'{internal["t"]} question: {internal["ins"].replace(tok.mask_token, " ")}', add_special_tokens=False)["input_ids"]
            original_options = [len(encode_text(tok, " " + text.replace(tok.mask_token, " "), add_special_tokens=False)["input_ids"]) + 1 for text in namespace["render_options"](internal)]
            if q.get("option_order") is not None:
                original_options = [original_options[i] for i in q["option_order"]]
            clipped_options = [min(n, 49, stats["tokens_per_option"] or n) for n in original_options]
            expected.append({"id": qid, "input_ids": seq, "marker_pos": markers,
                             "qtype": {"choice": 0, "score": 1, "yes_no": 2}[kind],
                             "state_tokens": state_stats["state_tokens"], "state_tokens_dropped": state_stats["state_tokens_dropped"],
                             "options_total": stats["options"], "options_distinct": stats["options_distinct"], "tokens_per_option": stats["tokens_per_option"],
                             "instruction_tokens_dropped": max(0, len(full_head) - max(8, head_max_len-sum(clipped_options))),
                             "option_tokens_dropped": [n-c for n,c in zip(original_options,clipped_options)]})
        results.append({"name": name, "request": {"state": state, "questions": questions},
                        "options": {"max_len": max_len, "head_max_len": head_max_len, "overflow": "allow_with_diagnostics"},
                        "expected": expected, "tokenizations": tokenizations})
    result = {"source": {"code_revision": CODE_REVISION, "model_revision": MODEL_REVISION,
                          "checkpoint": checkpoint,
                          "common_sha256": hashlib.sha256(source_bytes).hexdigest(),
                          "tokenizer_sha256": hashlib.sha256((tokenizer_dir / "tokenizer.json").read_bytes()).hexdigest(),
                          "packages": {p: importlib.metadata.version(p) for p in ("transformers", "tokenizers")}},
              "special_tokens": {"cls": tok.cls_token_id, "sep": tok.sep_token_id, "pad": tok.pad_token_id, "mask": tok.mask_token_id, "mask_text": tok.mask_token},
              "cases": results}
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(json.dumps(result, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Recorded {len(results)} cases in {output}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--tokenizer", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--checkpoint", choices=["english", "multilingual", "typed-decisions"], default="english")
    parser.add_argument("--permutations-only", action="store_true")
    args = parser.parse_args()
    record(args.source, args.tokenizer, args.output, args.checkpoint, args.permutations_only)
